### ISSUE TITLE
Skipping frames on the loading animation

### ISSUE THREAD

**Issue by anaximeno** [ful1e5/cbmp#1]
While testing the beta version of Linux Mint 21.1, I noticed some glitches in the animation of the Bibata Cursors. As you may see below, some frames are missing in the following sequences:

![Captura de ecrã de 2022-12-14 00-52-22](https://user-images.githubusercontent.com/63073056/207488675-db7e6608-4347-4e5a-88ce-b1461df0e1fe.png)

![Captura de ecrã de 2022-12-14 01-11-19](https://user-images.githubusercontent.com/63073056/207488684-57f4de25-a385-452b-9300-b5aa8799fb9e.png)

Those bitmaps where rendered by me on my computer using the ```yarn render``` command.

**Comment by anaximeno** [comment]
I have found this package https://github.com/benwiley4000/gif-frames I didn't test it, so I am not sure if it could be used (in some way) to fix the issue.

**Comment by ful1e5** [comment]
> I have found this package https://github.com/benwiley4000/gif-frames I didn't test it, so I am not sure if it could be used (in some way) to fix the issue.

I tried, but it couldn't parse the SVG animation file. We'll need to implement a custom workflow to address this issue.
